security:
    providers:
        frontastic:
            id: Frontastic\Common\AccountApiBundle\Security\AccountProvider

    encoders:
        Frontastic\Common\AccountApiBundle\Domain\Account: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        assests:
            pattern: ^/(_(profiler|wdt)|assets)/
            security: false

        replicator:
            pattern: ^/api/endpoint
            stateless: true
            security: false

        main:
            pattern: ^/
            anonymous: ~
            logout:
                path: /api/account/logout # Use route ID
                success_handler: Frontastic\Common\AccountApiBundle\Security\LogoutSuccessHandler
            guard:
                authenticators:
                    - Frontastic\Common\AccountApiBundle\Security\Authenticator

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
